#!/bin/bash

if ! which cmake >/dev/null 2>&1; then
    echo "CMAKE not found."
    exit 1
fi
if which clang >/dev/null 2>&1; then
	export CC=clang
	export CXX=clang
fi

configure_debug() {
	mkdir -p debug
	cd debug
	cmake -DCMAKE_BUILD_TYPE=Debug -G Ninja ..
	cd ..
}

configure_release() {
	mkdir -p release
	cd release
	cmake -DCMAKE_BUILD_TYPE=Release -G Ninja ..
	cd ..
}

if [ "$1x" == "configurex" ]; then
    rm -rf obj
	configure_debug
	configure_release
	exit $?
fi

if [ "$1x" == "cleanx" ]; then
	[[ ! -d debug ]] && configure_debug
	[[ ! -d release ]] && configure_release
	cd debug
	ninja clean
	cd ../release
	ninja clean
	cd ..
	exit 0
fi

build_debug() {
	[[ ! -d debug ]] && configure_debug
	cd debug
	ninja "$@"
	cd ..
}

build_release() {
	[[ ! -d release ]] && configure_release
	cd release
	ninja "$@"
	cd ..
}

case $1 in
	debug)
		shift
		build_debug
		;;
	release)
		shift
		build_release
		;;
	*)
		build_release
		;;
esac
