#!/bin/bash

configure() {
	if ! which cmake >/dev/null 2>&1; then
        echo "CMAKE not found."
        exit 1
	fi
	which clang >/dev/null 2>&1 && CC=clang
	export CC
	mkdir -p obj
	cd obj
	cmake -G Ninja ..
	cd ..
}

if [ "$1x" == "cleanx" ]; then
    rm -rf obj
	exit $?
fi

[[ ! -d obj ]] && configure
cd obj
ninja "$@"
cd ..
cp obj/roam ./roam
